### ISSUE TITLE
CSS variables support

### ISSUE THREAD

**Issue by sawa-ko** [rexcape/tailwindcss-antdesign-preset#1]
Currently I see that the primary colors, use a certain color, which prevents to change the primary color from the ant design theme options (I guess).

Ant design is compatible with css variables by enabling it in a simple way through the option:

```tsx
<ConfigProvider theme={{ cssVar: true }}>{children}</ConfigProvider>
```

## Result

![image](https://github.com/rexcape/tailwindcss-antdesign-preset/assets/56084970/51bec6eb-4d5f-4a5f-a1a4-d03111dc1b5e)

![image](https://github.com/rexcape/tailwindcss-antdesign-preset/assets/56084970/ca229ea0-003e-45a7-a23f-9ad844f79c73)

Also, tailwindcss accepts css variables such as color values, etc. It would be great if it worked that way, so you can customize the ant design theme from its options and tailwindcss configuration is always in sync.

**Comment by rexcape** [comment]
> Currently I see that the primary colors, use a certain color, which prevents to change the primary color from the ant design theme options (I guess).

Actually, you **can** change the primary color with ant design theme [token option](https://ant.design/docs/react/customize-theme#seedtoken):

```js
require('tailwindcss-antdesign-preset')({ colorPrimary: '#1677ff' })
```

the package will use the token value and ant design's [Consume Design Token](https://ant.design/docs/react/customize-theme#consume-design-token) to generate tailwindcss preset.

Sorry about that I didn't write it clearly in the readme. If this is not what you want or this doesn't work, you can leave a message.
