### ISSUE TITLE
使用之后border-solid和taiwind默认样式冲突

### ISSUE THREAD

**Issue by Renderz** [rexcape/tailwindcss-antdesign-preset#2]
border-solid 在tailwind里表示border-style = solid
  这里面拓展成了color，导致使用时直接给border-color赋值了

  不知道是不是这样引用会好一些: xxx-antd-primary？，不然感觉除此之外也许还有别的冲突的

   primary: '#1677ff',
   success: '#52c41a',
   warning: '#faad14',
   error: '#ff4d4f',
   info: '#1677ff',
   link: '#1677ff',
   'text-base': '#000',
   base: '#fff',
   textc: 'rgba(0, 0, 0, 0.88)',
   'text-secondary': 'rgba(0, 0, 0, 0.65)',
   'text-tertiary': 'rgba(0, 0, 0, 0.45)',
   'text-quaternary': 'rgba(0, 0, 0, 0.25)',
   fill: 'rgba(0, 0, 0, 0.15)',
   'fill-secondary': 'rgba(0, 0, 0, 0.06)',
   'fill-tertiary': 'rgba(0, 0, 0, 0.04)',
   'fill-quaternary': 'rgba(0, 0, 0, 0.02)',
   **solid: 'rgb(0, 0, 0)',**
   'solid-hover': 'rgba(0, 0, 0, 0.75)',
   'solid-active': 'rgba(0, 0, 0, 0.95)',
   layout: '#f5f5f5',
   container: '#ffffff',
   elevated: '#ffffff',
   spotlight: 'rgba(0, 0, 0, 0.85)',
   blur: 'transparent',
   border: '#d9d9d9',
   'border-secondary': '#f0f0f0',
   'primary-bg': '#e6f4ff',
   'primary-hover': '#4096ff',
   'primary-border': '#91caff',
   'primary-border-hover': '#69b1ff',
   'primary-active': '#0958d9',
   'primary-text-hover': '#4096ff',
   'primary-text': '#1677ff',
   'primary-text-active': '#0958d9',
   'success-bg': '#f6ffed',
   'success-hover': '#95de64',
   'success-border': '#b7eb8f',
   'success-border-hover': '#95de64',
   'success-active': '#389e0d',
   'success-text-hover': '#73d13d',
   'success-text': '#52c41a',
   'success-text-active': '#389e0d',
   'error-bg': '#fff2f0',
   'error-hover': '#ff7875',
   'error-filled-hover': '#ffdfdc',
   'error-active': '#d9363e',
   'error-border': '#ffccc7',
   'error-border-hover': '#ffa39e',
   'error-text-hover': '#ff7875',
   'error-text': '#ff4d4f',
   'error-text-active': '#d9363e',
   'warning-bg': '#fffbe6',
   'warning-hover': '#ffd666',
   'warning-border': '#ffe58f',
   'warning-border-hover': '#ffd666',
   'warning-active': '#d48806',
   'warning-text-hover': '#ffc53d',
   'warning-text': '#faad14',
   'warning-text-active': '#d48806',
   'info-bg': '#e6f4ff',
   'info-hover': '#69b1ff',
   'info-border': '#91caff',
   'info-border-hover': '#69b1ff',
   'info-active': '#0958d9',
   'info-text-hover': '#4096ff',
   'info-text': '#1677ff',
   'info-text-active': '#0958d9',
   'link-hover': '#69b1ff',
   'link-active': '#0958d9',
   mask: 'rgba(0, 0, 0, 0.45)',
   white: '#fff',
   'fill-content': 'rgba(0, 0, 0, 0.06)',
   'fill-content-hover': 'rgba(0, 0, 0, 0.15)',
   'fill-alter': 'rgba(0, 0, 0, 0.02)',
   'container-disabled': 'rgba(0, 0, 0, 0.04)',
   'border-bg': '#ffffff',
   split: 'rgba(5, 5, 5, 0.06)',
   'text-placeholder': 'rgba(0, 0, 0, 0.25)',
   'text-disabled': 'rgba(0, 0, 0, 0.25)',
   'text-heading': 'rgba(0, 0, 0, 0.88)',
   'text-label': 'rgba(0, 0, 0, 0.65)',
   'text-description': 'rgba(0, 0, 0, 0.45)',
   'text-light-solid': '#fff',
   highlight: '#ff4d4f',
   'text-hover': 'rgba(0, 0, 0, 0.06)',
   'text-active': 'rgba(0, 0, 0, 0.15)',
   iconc: 'rgba(0, 0, 0, 0.45)',
   'icon-hover': 'rgba(0, 0, 0, 0.88)',
   'error-outline': 'rgba(255, 38, 5, 0.06)',
   'warning-outline': 'rgba(255, 215, 5, 0.1)'

**Comment by rexcape** [comment]
用的时候确实没考虑到这个情况，应该给所有 ant 的颜色加一个前缀。没想好要怎么加：

- `antd` 作为前缀：使用者知道该 token 是 ant design 的，但是无法知道这个 token 是个颜色
- `color` 作为前缀：使用者知道该 token 是一个颜色，但是无法知道这个 token 是 ant design 的

这两种需要考虑一下。（并且加了这个前缀会让带有颜色的类名字很长）

**Comment by Renderz** [comment]
> 用的时候确实没考虑到这个情况，应该给所有 ant 的颜色加一个前缀。没想好要怎么加：
> 
> * `antd` 作为前缀：使用者知道该 token 是 ant design 的，但是无法知道这个 token 是个颜色
> * `color` 作为前缀：使用者知道该 token 是一个颜色，但是无法知道这个 token 是 ant design 的
> 
> 这两种需要考虑一下。（并且加了这个前缀会让带有颜色的类名字很长）

确实，感觉加了也挺奇怪。
或者允许用户自定义prefix之类的操作？

**Comment by rexcape** [comment]
颜色的冲突改好了，不知道除了颜色之外还有没有其他的冲突，组合实在太多了。

**Comment by rexcape** [comment]
写了个简单的[网页生成器](https://rexcape.github.io/tailwindcss-antdesign-preset/)，根据 [antdesign theme editor](https://ant.design/theme-editor) 主题配置生成 tailwind 配置，可以自由修改、直接放到 `tailwind.config.js` 里。如果网页生成器有问题可以在另外的 issue 里写。这个 issue 先关了
